### ISSUE TITLE
OTP Form error messages

### ISSUE THREAD

**Issue by cyril2day** [markheramis/laravel-restful-api#24]
Perhaps we should not return error messages like "The code must be a string" or "The code field is required" when OTP validation fails. It should be something user friendly like `The code is invalid` or `The code is required` or `Code must be atleast 6 characters`
![Screenshot_2022-04-13_08-52-46](https://user-images.githubusercontent.com/13097392/163078202-55cf8fe6-ffd3-4f20-8490-5367e6dacae9.png)

**Comment by markheramis** [comment]
OTP is now removed from this repository
